ucsb-cs148-w25/pj12-closettracker

team/NORMS.md

- add team norms
- feel free to edit

GL - create team norms

---

team/victor.md

my personal file

---

team/Daisy.md

intro, yippee

---

closet-tracker/app.json
closet-tracker/hooks/useImagePicker.ts
closet-tracker/image_picker_ex.tsx
closet-tracker/package.json

created useImagePicker.tsx to allow easier image selecting and capturing development.
Ran reset-project to remove example app.
closes https://github.com/ucsb-cs148-w25/pj12-closettracker/issues/31

image picker hooks completed

---

closet-tracker/app/(tabs)/upload.tsx

- removed safeareaview to enable scrolling
- changed background of text and text color to remain readable regardless of light/dark mode
- added options to replace selected image with one from camera roll or camera
closes #56 
https://github.com/user-attachments/assets/fffdaad5-b1ed-449a-a384-6963be5f4972

fix upload page scroll and edit ui components

---

closet-tracker/.gitignore
closet-tracker/app/(login)/signup.tsx
closet-tracker/app/(tabs)/index.tsx
closet-tracker/app/(tabs)/wardrobe.tsx
closet-tracker/package-lock.json
closet-tracker/package.json

https://github.com/user-attachments/assets/098cddc0-25b8-40c9-9c30-0fab0fea47db
New Pull Request!!!
So now auth sign in page adds user to the database in firebase.
Each user in the firebase collection has their name, email, and id set up.
Also when a new user is created, an empty subcollection is initialized for them.
The subcollection is called clothing!
All these things that are initialized ONLY apply to new users, users that already exists do NOT have their user meta data in the database. So you might have to remove old users from authentication and make new ones, or manually add the users onto the database.
Now in the subcollection of the user im testing, I have manually included some clothing items.
For the image part, since firebase storage is not free anymore **I used supabase …

Andrew database to wardrobe

---

closet-tracker/app/(screens)/singleItem.tsx
closet-tracker/app/(tabs)/wardrobe.tsx
closet-tracker/components/SingleItemComponents.tsx

Changed clothing to single item page.
Added some button features and layout design in single item components.
https://github.com/user-attachments/assets/ecbdb26a-71ad-4d38-8887-ed1b310b155f

Added a visual feature for tracking clothes in singleItem page

---

closet-tracker/app/(screens)/_layout.tsx
closet-tracker/app/(screens)/singleItem.tsx

https://github.com/user-attachments/assets/b2c50acf-8e5e-45df-982f-4e12e2dbc2df
On the singleItem page, instead of using dummy data, I fetched the data of the item from the firebase. No need for dummy data anymore!
For the people working on functionalities of the singleItem page, I hashed out the handle increment so you guys can start adding those functionalities on top of my code.

Linked SingleItem Page to use firebase and supabase

---

closet-tracker/app/(tabs)/wardrobe.tsx

Icon for laundry button now matches the colors on the wardrobe page

Changed color of laundry icon

---

closet-tracker/app/(login)/signup.tsx

- there is now a second password input on signup page
- if entering mismatching passwords, an alert will pop up saying "passwords do not match"
- passwords must match in order to sign up
closes #89

added second password input on signup

---

closet-tracker/app/(tabs)/user.tsx

- user profile page now has profile picture, description, and stats showing number of clothes and most worn item (note that this stat just takes the first img in ur wardrobe. we need the wearCount metadata for this. OR we can change this stat entirely)
- created a new bucket on supabase called profilePictures to retrieve public URLs of pfps
- added new data to users on firebase: description and profilePicture
- users can press "Edit Profile" to update their pfps and descriptions, which will be saved across devices per acct
- changes will not be saved if user presses "Cancel"
closes #96 
https://github.com/user-attachments/assets/f41e9fe3-d734-4f9a-88aa-8a735f29f281

add user profile stuff (pfp, description, stats)

---

closet-tracker/app/(screens)/uploadClothingData.tsx
closet-tracker/app/(tabs)/wardrobe.tsx
closet-tracker/components/UploadClothingComponents.tsx

This adds an edit button to the wardrobe page and allows you to edit only one item at a time. 
The button brings you to the UploadClothingComponents page and this page now displays all the clothing's current data from the fire base. 
Something we can add is a back button. 
Better UI. 
The ability to the edit the users photos.
https://github.com/user-attachments/assets/397e6ca7-0b90-4ef5-b1e2-ca330e2ec625

Victor nardi

---

closet-tracker/app/(screens)/_layout.tsx
closet-tracker/app/(screens)/createOutfit.tsx
closet-tracker/app/(tabs)/outfit.tsx
closet-tracker/app/(tabs)/wardrobe.tsx
closet-tracker/components/ClothingItem.tsx
closet-tracker/components/MultiSelectActions.tsx
closet-tracker/components/searchBar.tsx

https://github.com/user-attachments/assets/5c86647e-cc6d-4b98-b605-91e34195a5d4
Ok It looks lowk ugly rn I didn't style the buttons
BUT
I created three new components both used in wardrobe and create outfit page
The video shows the that on the wardrobe page you can no longer create outfits, that can only be done on the create outfit page.
The create outfit page doesn't have delete or edit.
closes #111

BIG Changes in wardrobe page! Created Components for Modularity so I don't repeat code PLUS Create Outfit Page

---

closet-tracker/app/(screens)/createOutfit.tsx
closet-tracker/app/(screens)/editItem.tsx
closet-tracker/app/(screens)/laundry.tsx
closet-tracker/app/(tabs)/user.tsx
closet-tracker/app/(tabs)/wardrobe.tsx
closet-tracker/components/MultiSelectActions.tsx
closet-tracker/components/UploadClothingComponents.tsx
closet-tracker/components/UploadOutfitComponents.tsx

Changes:
- Fixed hardcoded user "most worn" item. now using actual most worn in Clothing collection
- Added option in MultiSelection component from andrew to hide cancel selection Mode for create outfit
- Applied Keyboard Avoiding from sophia to outfit edit component
- Applied all new features from outfit and clothing pages into laundry pipeline
- sort by date uploaded
- modular components and sections
- search bar
- connection with edit page
- connection with single item page
- dynamic checking of user state
https://github.com/user-attachments/assets/60cc770c-2fa4-4e2a-85e2-c4cc03fde796

Refactor 2/21

---

closet-tracker/app/(tabs)/wardrobe.tsx

- wardrobe page now has filter feature that lets users filter clothes by metadata (e.g. size, color, type of clothing, etc.)
- filter options now update dynamically. no filter options are available if a user has no clothes in their wardrobe. once they upload something (e.g. small pink t-shirt), the filter options will appear (size small, color pink, type t-shirt). more filter options appear as you have more variety in your wardrobe
- sizes xs -> xl will be ordered in ascending order
closes #80 
https://github.com/user-attachments/assets/7fdb89da-0867-4f61-97dc-2522f07dcbce

add dynamic filter feature for wardrobe page

---

closet-tracker/app/(screens)/createOutfit.tsx
closet-tracker/app/(screens)/laundry.tsx
closet-tracker/app/(tabs)/outfit.tsx
closet-tracker/app/(tabs)/wardrobe.tsx
closet-tracker/components/FilterModal.tsx
closet-tracker/components/UploadOutfitComponents.tsx
closet-tracker/components/searchBar.tsx

- flatlists looked different depending on content inside
- filter is a component now
- added to wardrobe, create outfit, laundry
https://github.com/user-attachments/assets/e1f9d10d-1d70-47f8-86e6-2d278dc0b7c7

Applied filter to all wardrobe type page; made filter modular

---

closet-tracker/app/(screens)/singleItem.tsx
closet-tracker/app/(tabs)/_layout.tsx
closet-tracker/app/(tabs)/home.tsx
closet-tracker/components/PublicItem.tsx

- GPT assisted
- home page shows clean and dirty items
- quick access button to clean everything (if user washed all)
- public section complete
- havent tested with multiple users
- can add and remove your own outfits into public
- can like and unlike other/your public outfits
- currently don't have any feature in single items page
https://github.com/user-attachments/assets/187239dc-430d-4565-beb6-20d0085ab6b8
closes #125

added home page

---

closet-tracker/app/(screens)/singleItem.tsx
closet-tracker/app/(tabs)/home.tsx
closet-tracker/components/PublicItem.tsx

Added loading state for:
- home page wash button
- home page public item like/unlike button
- outfit single item page private/public button

Bug Fix for home page

---

closet-tracker/app/(app)/(screens)/createOutfit.tsx
closet-tracker/app/(app)/(screens)/editItem.tsx
closet-tracker/app/(app)/(tabs)/index.tsx
closet-tracker/app/(app)/(tabs)/upload.tsx

All fixes:
- Upload page: if goback/cancel before submitting extra info, but after submitting image, will not be show up
- Fix: added dateuploaded in upload page, so clothing will still show up
- Home page: laundry and clean count did not update dynamically, and count during washing is weird
- Fix: added a temp state, so while loading the count will stop uploading, only update after
- Create outfit page: completely broken
- Fix: my bad, deleted important stuff during refactoring. added them back and should work now
- Submit from edit item page should go back to home but only went back 1

BUG FIX from Inter-team feedback

---

closet-tracker/app/(app)/(screens)/canvas.tsx

- can add profile picture to canvas when creating outfits through a toggle
- if no pfp uploaded yet, the toggle is not visible
- if pfp uploaded, toggle is visible
- when toggled on, pfp appears in layers and can be moved around
- pfp can be resized like clothing items on canvas
possible future sub issue:
- remove background of pfp to make it look nicer on canvas? (might be kinda extra + use up more of our background remover LOL)
closes #115 
https://github.com/user-attachments/assets/8b9c332b-ba8e-4300-a9a8-5e3298f6e5ed

add profile picture to canvas

---

closet-tracker/app/(app)/(tabs)/wardrobe.tsx

The background color of each wardrobe item changes based on wear count of the clothing item.
The color starts from beige and darkens as the wear count increases.
Background color function only added to wardrobe.tsx and color can be modified.
closes #22

Background Color of Wardrobe Items Change

---

closet-tracker/app/(app)/(screens)/singleItem.tsx
closet-tracker/app/_layout.tsx
closet-tracker/components/SingleItemComponents.tsx

This finishes the functionality of the singleItem page. 
- It imports TimesWornComponent from singleItemComponents.
- The TimesWornComponent directly interacts with the firebase to update the wearCount
- Edit button was added to the singleItem page
Future additions: 
- Bug discovered: editing the clothing causes wearCount to reset
- More UI design
- More cohesive color scheme 
https://github.com/user-attachments/assets/6870a0c4-84ef-44ce-bfc1-0d454a49ffb0

finished aesthetics and functionality for single item page

---

closet-tracker/aesthetic/beigeColors.ts
closet-tracker/app/(app)/(tabs)/_layout.tsx
closet-tracker/app/(app)/(tabs)/user.tsx
closet-tracker/components/ui/TabBarBackground.ios.tsx
closet-tracker/components/ui/TabBarBackground.tsx

Bottom bar color changed

---

closet-tracker/app/(app)/(screens)/editItem.tsx
closet-tracker/app/(app)/(screens)/singleItem.tsx
closet-tracker/app/(app)/(tabs)/outfit.tsx

Removed wearcount from outfits, changed color to match theme
